# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4ae50f96f3f8c6ef4f269f27aa4e2ebf"
name = "UIA"
application_url = "https://underitall.replit.app"
embedded = true

[build]
dev_store_url = "underitall-dev.myshopify.com"

[webhooks]
api_version = "2025-10"

[access_scopes]
scopes = "read_orders,read_products,read_customers"
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
optional_scopes = [ ]
use_legacy_install_flow = false

[pos]
embedded = false

[auth]
redirect_urls = [
  "https://underitall.replit.app/auth/callback",
  "https://underitall.replit.app/auth/shopify/callback",
  "https://underitall.replit.app/api/auth/callback"
]

