api_version = "2025-01"

[[extensions]]
name = "order-report-cards"
handle = "order-report-cards"
uid = "9067fbaf-8b35-e61f-bdc7-6ec708a1fef3efcd2a92"
type = "ui_extension"


[[extensions.targeting]]
module = "./src/PrintActionExtension.jsx"
target = "admin.order-details.print-action.render"
