
# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "report-card-generator"
client_id = "YOUR_CLIENT_ID_HERE"
application_url = "https://your-actual-repl-url.repl.co"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "YOUR_DEV_STORE.myshopify.com"

[access_scopes]
scopes = "read_orders"

[auth]
redirect_urls = [
  "https://your-actual-repl-url.repl.co/auth/callback"
]

[webhooks]
api_version = "2025-01"

[pos]
embedded = false
